import classNames from "classnames";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";

import type { Metadata } from "next";

import { theme } from "@/constants/theme";
import { BalooFont } from "@/constants/fonts";

import '@mantine/core/styles.css';
import '@mantine/charts/styles.css';
import "./globals.css";

export const metadata: Metadata = {
  title: "Agent App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ColorSchemeScript defaultColorScheme='light' />
      </head>
      <body
        className={classNames(BalooFont.className)}
      >
        <MantineProvider theme={theme}>
          {children}
        </MantineProvider>
      </body>
    </html>
  );
}
